import type { Metadata } from "next";
import { Quicksand, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const quicksand = Quicksand({
    variable: "--font-quicksand",
    subsets: ["latin"],
});

const sourceSans3 = Source_Sans_3({
    variable: "--font-source-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${quicksand.variable} ${sourceSans3.variable} antialiased font-sans`}>
                <Nav />
                {children}
            </body>
        </html>
    );
}
